# vim:sw=2:et:

sudo: false
language: erlang
notifications:
  email:
    on_success: never
    on_failure: always
cache:
  apt: true

otp_release:
  - "21.0"
  - "22.0"


script:
  - make test xref dialyzer
